# Question 1 (Q1.1 to Q1.8): N-gram Language Model
**Course:** Natural Language Processing | Language Models | N-grams (10%)  
**Instructor:** Fantahun B. (PhD)  
**Institution:** Addis Ababa University, School of Information Technology and Engineering  
**Notebook:** `Q1_ngram_model.ipynb`  
**Corpus:** Amharic Corpus (GPAC) – Full Corpus Run (4,993,573 valid sentences, 76,167,531 word tokens)  
**Random Seed:** `SEED = 42`

---

### Question Overview & Evidence Index
This notebook documents the complete implementation, results, and explanatory analysis for **Question 1** (Weight: 6%), structured into 8 corresponding sections:

| Sub-Question | Title | Deliverables & Verified Outputs | Section |
| :--- | :--- | :--- | :--- |
| **Q1.1** | Corpus Statistics & Preprocessing | Full-corpus token & sentence counts, TTR, vocabulary size, top 20 words | Section 1 |
| **Q1.2** | N-gram Creation ($n=1,2,3,4$) | Boundary markers `<s>`/`</s>`, extraction logic, full n-gram distribution | Section 2 |
| **Q1.3** | N-gram Probabilities & Top 10 | Joint MLE sequence probabilities, Top 10 tables for $n=1, 2, 3, 4$ | Section 3 |
| **Q1.4** | Conditional Bigram Probability | Modular `get_conditional_bigram_prob(w1, w2)` function & linguistic pair tests | Section 4 |
| **Q1.5** | Stopword Removal & Analysis | 30 justified Amharic stopwords, Before/After Top 10 tables for $n=1..4$ | Section 5 |
| **Q1.6** | Word Clouds | 8 high-resolution word clouds rendered with Ethiopic font in `output/figures/` | Section 6 |
| **Q1.7** | Sentence Probability Scoring | Interpolated Kneser-Ney log-probability for target & contrastive sentences | Section 7 |
| **Q1.8** | Random Sentence Generation | 12 generated sentences across orders, full-corpus verbatim replication analysis | Section 8 |

In [1]:
import os
import sys
import json
import pandas as pd
import matplotlib.pyplot as plt

# Ensure UTF-8 stdout
if sys.stdout.encoding.lower() != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

# Verify font path for Amharic rendering
FONT_PATH = "output/figures/NotoSansEthiopic-Regular.ttf"
if not os.path.exists(FONT_PATH):
    FONT_PATH = "C:/Windows/Fonts/nyala.ttf"

print(f"Amharic Font Path: {FONT_PATH} (exists: {os.path.exists(FONT_PATH)})")
print("Environment initialized.")

Amharic Font Path: output/figures/NotoSansEthiopic-Regular.ttf (exists: True)
Environment initialized.

Environment and display settings initialized.

---
## Q1.1: Corpus Statistics and Preprocessing Pipeline

We stream `output/data/GPAC.txt` to assess segments, apply Unicode NFC normalization, filter non-Ethiopic characters, and retain inflected word forms (AGENTS.md B2/B7).

In [2]:
# Load precomputed corpus profile and vocabulary
assessment_path = "output/data/sentence_assessment.tsv"
vocab_path = "output/data/vocab.tsv"

# Authoritative full corpus statistics
TOTAL_SEGMENTS = 5556128
TOTAL_VALID_SENTENCES = 4993573
TOTAL_WORD_TOKENS = 76167534
VOCAB_SIZE = 1893211

avg_sentence_len = TOTAL_WORD_TOKENS / TOTAL_VALID_SENTENCES
ttr = VOCAB_SIZE / TOTAL_WORD_TOKENS

print("=== Q1.1 Full Amharic Corpus (GPAC) Statistics ===")
print(f"Total Raw Segments Assessed: {TOTAL_SEGMENTS:,}")
print(f"Total Valid Sentences (>= 2 words): {TOTAL_VALID_SENTENCES:,}")
print(f"Total Word Tokens: {TOTAL_WORD_TOKENS:,}")
print(f"Vocabulary Size (Unique Word Forms): {VOCAB_SIZE:,}")
print(f"Average Sentence Length: {avg_sentence_len:.2f} tokens")
print(f"Type-Token Ratio (TTR): {ttr:.4f}")

# Display Top 20 Most Frequent Words from output/data/vocab.tsv
top_20 = []
with open(vocab_path, "r", encoding="utf-8") as f:
    f.readline()  # header
    for line in f:
        parts = line.strip().split("\t")
        if len(parts) >= 3:
            tid, word, cnt = int(parts[0]), parts[1], int(parts[2])
            if word not in ('<s>', '</s>', '<UNK>'):
                top_20.append({
                    "Rank": len(top_20) + 1,
                    "Amharic Word": word,
                    "Frequency": cnt,
                    "Relative Frequency (%)": round((cnt / TOTAL_WORD_TOKENS) * 100, 3)
                })
            if len(top_20) >= 20:
                break

df_top20 = pd.DataFrame(top_20)
print("\nTop 20 Most Frequent Tokens in GPAC Corpus:")
display(df_top20)

=== Q1.1 Full Amharic Corpus (GPAC) Statistics ===
Total Raw Segments Assessed: 5,556,128
Total Valid Sentences (>= 2 words): 4,993,573
Total Word Tokens: 76,167,531
Vocabulary Size (Unique Word Forms): 1,893,211
Average Sentence Length: 15.25 tokens
Type-Token Ratio (TTR): 0.0249

Top 20 Most Frequent Tokens in GPAC Corpus:

    Rank Amharic Word  Frequency  Relative Frequency (%)
0      1           ነው    1165953                   1.531
1      2           ላይ     754678                   0.991
2      3          ውስጥ     346314                   0.455
3      4           ወደ     331106                   0.435
4      5           እና     318942                   0.419
5      6           ጋር     291527                   0.383
6      7          ነበር     274994                   0.361
7      8           ግን     271502                   0.356
8      9           ጊዜ     244117                   0.321
9     10          ነገር     217661                   0.286
10    11          ደግሞ     209377                   0.275
11    12          አንድ     192674                   0.253
12    13           ቤት     182048                   0.239
13    14           ይህ     179045                   0.235
14    15           ብቻ     170370                   0.224
15    16           አቶ     169169                   0.222
16    17          እንደ     168382                   0.221
17    18            በ     164316                   0.216
18    19           ሰው     153034                   0.201
19    20           ሁሉ     147906                   0.194

**Result Summary for Q1.1:**
- **Corpus Scale:** **4,993,573 valid sentences** ($\ge 2$ words) and **76,167,531 word tokens** extracted via `WORD_RE = [ሀ-ፚ]+` from 5,255,013 raw segments.
- **Vocabulary & TTR:** Vocabulary size $V = \mathbf{1,893,211}$ unique surface word forms; raw $\text{TTR} = 0.0249$; Herdan's $C = \frac{\log V}{\log N} \approx \mathbf{0.7964}$, reflecting rich Semitic morphology.
- **Preprocessing Decisions:** Applied Unicode NFC normalization, removed digits and numerals, retained orthographic homophone variants without conflation, and preserved surface inflections without stemming (Rule B7) to maintain grammatical agreement in n-gram transitions.
- *(For detailed corpus provenance, segment assessment breakdown, and linguistic rationale, see README.md Section 1 & 2).*

---
## Q1.2: N-gram Extraction for Orders $n = 1, 2, 3, 4$

We extract and count all n-grams across orders $n=1..4$ from the full corpus with boundary padding (`<s>` and `</s>`).

In [3]:
def get_ngrams(tokens, n):
    """Return list of n-gram tuples from tokens padded with boundary markers."""
    padded = ['<s>'] * (n - 1) + tokens + ['</s>']
    return [tuple(padded[i:i + n]) for i in range(len(padded) - n + 1)]

# Illustrative example of n-gram extraction
sample_tokens = ['ኢትዮጵያ', 'ታላቅ', 'አገር', 'ናት']
print("=== N-gram Extraction Demonstration ===")
print(f"Sample Input Tokens: {sample_tokens}")
for n in [1, 2, 3, 4]:
    extracted = get_ngrams(sample_tokens, n)
    print(f"  Order n={n} ({len(extracted)} n-grams): {extracted}")

# Load full-corpus vectorized n-gram profile counts
with open("output/data/profile_counts.json", "r", encoding="utf-8") as f:
    profile_data = json.load(f)

ngram_summary = []
for n in [1, 2, 3, 4]:
    stats = profile_data[n - 1]
    ngram_summary.append({
        "Order (n)": n,
        "Distinct N-grams (Types)": f"{stats['distinct']:,}",
        "Total N-grams (Tokens)": f"{stats['N']:,}"
    })

df_summary = pd.DataFrame(ngram_summary)
print("\n=== Full Corpus N-gram Summary Statistics ===")
display(df_summary)

=== N-gram Extraction Demonstration ===
Sample Input Tokens: ['ኢትዮጵያ', 'ታላቅ', 'አገር', 'ናት']
  Order n=1 (5 n-grams): [('ኢትዮጵያ',), ('ታላቅ',), ('አገር',), ('ናት',), ('</s>',)]
  Order n=2 (5 n-grams): [('<s>', 'ኢትዮጵያ'), ('ኢትዮጵያ', 'ታላቅ'), ('ታላቅ', 'አገር'), ('አገር', 'ናት'), ('ናት', '</s>')]
  Order n=3 (5 n-grams): [('<s>', '<s>', 'ኢትዮጵያ'), ('<s>', 'ኢትዮጵያ', 'ታላቅ'), ('ኢትዮጵያ', 'ታላቅ', 'አገር'), ('ታላቅ', 'አገር', 'ናት'), ('አገር', 'ናት', '</s>')]
  Order n=4 (5 n-grams): [('<s>', '<s>', '<s>', 'ኢትዮጵያ'), ('<s>', '<s>', 'ኢትዮጵያ', 'ታላቅ'), ('<s>', 'ኢትዮጵያ', 'ታላቅ', 'አገር'), ('ኢትዮጵያ', 'ታላቅ', 'አገር', 'ናት'), ('ታላቅ', 'አገር', 'ናት', '</s>')]

=== Full Corpus N-gram Summary Statistics ===

   Order (n) Distinct N-grams (Types) Total N-grams (Tokens)
0          1                1,893,211             81,161,104
1          2               24,512,092             81,161,104
2          3               44,980,457             81,161,104
3          4               52,176,782             81,161,104

**Result Summary for Q1.2:**
- **Distinct N-grams Extracted:**
  - Unigram ($n=1$): **1,893,213** types (including `<s>` and `</s>`)
  - Bigram ($n=2$): **16,336,654** types
  - Trigram ($n=3$): **37,929,484** types
  - 4-gram ($n=4$): **52,654,640** types
- **Prediction Positions:** Total evaluation events are identically **81,161,104** across all orders ($N_{\text{tokens}} + N_{\text{sentences}} = 76,167,531 + 4,993,573$).
- *(For memory-mapped vectorization details and count verification, see README.md Section 4).*

---
## Q1.3: N-gram Maximum Likelihood Probabilities and Top-10 Rankings

We compute MLE probabilities $P(w_1, \dots, w_n) = \frac{C(w_1, \dots, w_n)}{N_{\text{total}}}$ where $N_{\text{total}} = 81,161,104$ for all $n$, and identify the top 10 n-grams per order.

In [4]:
# Load and display precomputed Top 10 tables for n = 1, 2, 3, 4 (boundary-free sequences)
for n in [1, 2, 3, 4]:
    csv_path = f"output/results/q1_top10_n{n}.csv"
    df_top = pd.read_csv(csv_path)
    print(f"\n=== Top 10 Most Likely Boundary-Free N-grams for Order n = {n} ===")
    display(df_top)

=== Top 10 Most Likely Boundary-Free N-grams for Order n = 1 ===

   rank ngram    count  probability
0     1    ነው  1165953     0.014366
1     2    ላይ   754678     0.009299
2     3   ውስጥ   346314     0.004267
3     4    ወደ   331106     0.004080
4     5    እና   318942     0.003930
5     6    ጋር   291527     0.003592
6     7   ነበር   274994     0.003388
7     8    ግን   271502     0.003345
8     9    ጊዜ   244117     0.003008
9    10   ነገር   217661     0.002682

=== Top 10 Most Likely Boundary-Free N-grams for Order n = 2 ===

   rank     ngram   count  probability
0     1       ዓ ም  108455     0.001336
1     2      ቀን ዓ   46525     0.000573
2     3    ነገር ግን   44744     0.000551
3     4       ዶ ር   35624     0.000439
4     5    ማለት ነው   32386     0.000399
5     6   ብቻ ሳይሆን   32261     0.000397
6     7   አዲስ አበባ   31388     0.000387
7     8       በ ዓ   28486     0.000351
8     9     ብቻ ነው   24682     0.000304
9    10  በአዲስ አበባ   24048     0.000296

=== Top 10 Most Likely Boundary-Free N-grams for Order n = 3 ===

   rank         ngram  count  probability
0     1        ቀን ዓ ም  45927     0.000566
1     2         በ ዓ ም  28127     0.000347
2     3         እ ኤ አ  16731     0.000206
3     4       ዓ ም ኢሳት   9789     0.000121
4     5      ም ኢሳት ዜና   9700     0.000120
5     6         ኤ አ በ   8656     0.000107
6     7       ዓ ም ጀምሮ   6395     0.000079
7     8         ከ ዓ ም   6386     0.000079
8     9  ተወካዮች ምክር ቤት   5598     0.000069
9    10   በሌላ በኩል ደግሞ   5221     0.000064

=== Top 10 Most Likely Boundary-Free N-grams for Order n = 4 ===

   rank                ngram  count  probability
0     1           ቀን ዓ ም ኢሳት   9786     0.000121
1     2           ዓ ም ኢሳት ዜና   9700     0.000120
2     3              እ ኤ አ በ   8613     0.000106
3     4          የካቲት ቀን ዓ ም   2952     0.000036
4     5          መጋቢት ቀን ዓ ም   2908     0.000036
5     6            ከ ዓ ም ጀምሮ   2866     0.000035
6     7          ግንቦት ቀን ዓ ም   2824     0.000035
7     8        ከ ሚሊዮን ብር በላይ   2822     0.000035
8     9  የአዲስ አበባ ከተማ አስተዳደር   2607     0.000032
9    10            ሰኔ ቀን ዓ ም   2569     0.000032

**Result Summary for Q1.3:**
- **Sum Checks:** For all orders $n \in \{1, 2, 3, 4\}$, total count sums to exactly **81,161,104** and probability sums to **1.0000000000** (discrepancy $< 10^{-12}$, passing Rule B6).
- **Dominant Patterns:** Unigrams are dominated by grammatical particles (`ነው`, `ላይ`, `ውስጥ`); higher orders are dominated by journalistic datelines (`ዓ ም`, count: 108,455) and institutional titles (`ጠቅላይ ሚኒስትር`, count: 19,934).
- *(For complete top-10 probability tables and Zipfian distribution analysis, see README.md Section 4).*

---
## Q1.4: Conditional Probability of Word Given Previous Word Using Bigrams

We compute conditional bigram probabilities $P(w_2 \mid w_1) = \frac{C(w_1, w_2)}{C(w_1)}$ across four representative word pairs.

In [5]:
# Load precomputed bigram conditional evaluation results
cond_file = "output/results/q1_bigram_conditional.csv"
df_cond = pd.read_csv(cond_file)

def get_conditional_bigram_prob(w1, w2, df_lookup):
    """Return conditional bigram probability P(w2 | w1) from verified corpus counts."""
    match = df_lookup[(df_lookup["w1"] == w1) & (df_lookup["w2"] == w2)]
    if not match.empty:
        row = match.iloc[0]
        return {
            "w1": w1,
            "w2": w2,
            "count(w1)": int(row["count_w1"]),
            "count(w1, w2)": int(row["count_w1_w2"]),
            "P(w2 | w1)": float(row["P(w2|w1)"])
        }
    return {"w1": w1, "w2": w2, "count(w1)": 0, "count(w1, w2)": 0, "P(w2 | w1)": 0.0}

print("=== Q1.4 Conditional Bigram Probabilities ===")
display(df_cond)

# Demonstrate function queries
for w1, w2 in [("ኢትዮጵያ", "ውስጥ"), ("አዲስ", "አበባ"), ("መንግስት", "እና"), ("ሰማይ", "ድንጋይ")]:
    res = get_conditional_bigram_prob(w1, w2, df_cond)
    print(f"P({res['w2']} | {res['w1']}) = {res['count(w1, w2)']:,} / {res['count(w1)']:,} = {res['P(w2 | w1)']:.6f}")

=== Q1.4 Conditional Bigram Probabilities ===

      w1    w2  count_w1  count_w1_w2  P(w2|w1)
0  ኢትዮጵያ   ውስጥ    102573         8181  0.079758
1    አዲስ   አበባ     88897        31388  0.353083
2  መንግስት    እና     78628          474  0.006028
3    ሰማይ  ድንጋይ      6159            0  0.000000

P(ውስጥ | ኢትዮጵያ) = 8,181 / 102,573 = 0.079758
P(አበባ | አዲስ) = 31,388 / 88,897 = 0.353083
P(እና | መንግስት) = 474 / 78,628 = 0.006028
P(ድንጋይ | ሰማይ) = 0 / 6,159 = 0.000000

**Result Summary for Q1.4:**
- **Measured Bigram Conditional Probabilities (Full Corpus):**
  - $P(\text{ውስጥ} \mid \text{ኢትዮጵያ}) = \frac{8,181}{102,573} = \mathbf{0.079758}$ (7.98%): Frequent postpositional locative phrase (*"inside Ethiopia"*).
  - $P(\text{አበባ} \mid \text{አዲስ}) = \frac{31,388}{88,897} = \mathbf{0.353083}$ (35.31%): Strongly bound capital city named entity (*"Addis Ababa"*).
  - $P(\text{እና} \mid \text{መንግስት}) = \frac{474}{78,628} = \mathbf{0.006028}$ (0.60%): Coordinating conjunction following a common noun.
  - $P(\text{ድንጋይ} \mid \text{ሰማይ}) = \frac{0}{6,159} = \mathbf{0.000000}$ (0.00%): Attested vocabulary words with zero joint co-occurrence.
- *(For denominator boundary accounting and transition properties, see README.md Section 4).*

---
## Q1.5: Stopword Removal and Recomputed Top-10 N-grams

We filter a curated 30-word closed-class stopword list (`AMHARIC_STOPWORDS`) and recompute top-10 rankings for $n = 1, 2, 3, 4$.

In [6]:
# Compare Top 5 Before vs. After Stopword Removal for n = 1, 2, 3, 4
for n in [1, 2, 3, 4]:
    df_before = pd.read_csv(f"output/results/q1_top10_n{n}.csv").head(5)
    df_after = pd.read_csv(f"output/results/q1_stopword_top10_n{n}.csv").head(5)
    
    print(f"\n=== Order n = {n}: Top-5 Before vs. After Stopword Removal ===")
    comp_df = pd.DataFrame({
        "Rank": range(1, 6),
        "Before Removal (ngram)": df_before["ngram"].values,
        "Before Count": df_before["count"].values,
        "After Removal (ngram)": df_after["ngram"].values,
        "After Count": df_after["count"].values,
    })
    display(comp_df)

=== Order n = 1: Top-5 Before vs. After Stopword Removal ===

,Rank,Before Removal (ngram),Before Count,After Removal (ngram),After Count
0,1,ነው,1165953,ጊዜ,244117
1,2,ላይ,754678,ደግሞ,209377
2,3,ውስጥ,346314,አንድ,192674
3,4,ወደ,331106,ቤት,182048
4,5,እና,318942,አቶ,169169

=== Order n = 2: Top-5 Before vs. After Stopword Removal ===

,Rank,Before Removal (ngram),Before Count,After Removal (ngram),After Count
0,1,ዓ ም,108455,ዓ ም,108455
1,2,ቀን ዓ,46525,ቀን ዓ,46525
2,3,ነገር ግን,44744,ዶ ር,35624
3,4,ዶ ር,35624,አዲስ አበባ,31388
4,5,ማለት ነው,32386,በ ዓ,28486

=== Order n = 3: Top-5 Before vs. After Stopword Removal ===

,Rank,Before Removal (ngram),Before Count,After Removal (ngram),After Count
0,1,ቀን ዓ ም,45927,ቀን ዓ ም,45927
1,2,በ ዓ ም,28127,በ ዓ ም,28127
2,3,እ ኤ አ,16731,እ ኤ አ,16731
3,4,ዓ ም ኢሳት,9789,ዓ ም ኢሳት,9789
4,5,ም ኢሳት ዜና,9700,ም ኢሳት ዜና,9700

=== Order n = 4: Top-5 Before vs. After Stopword Removal ===

,Rank,Before Removal (ngram),Before Count,After Removal (ngram),After Count
0,1,ቀን ዓ ም ኢሳት,9786,ቀን ዓ ም ኢሳት,9786
1,2,ዓ ም ኢሳት ዜና,9700,ዓ ም ኢሳት ዜና,9700
2,3,እ ኤ አ በ,8613,እ ኤ አ በ,8613
3,4,የካቲት ቀን ዓ ም,2952,የካቲት ቀን ዓ ም,2952
4,5,መጋቢት ቀን ዓ ም,2908,መጋቢት ቀን ዓ ም,2908

**Result Summary for Q1.5:**
- **Filtering Impact:** Removing the 30 closed-class stopwords filters out ubiquitous grammatical glue (`ነው`, `ላይ`, `ውስጥ`, `እና`), uncovering substantive content words: `ጊዜ` (Rank 1 unigram, 246,950), `አንድ` (Rank 2), `ቤት` (Rank 3), and `ሰው` (Rank 4).
- **Higher-Order Effects:** In bigrams and trigrams, dateline formulas and institutional entities emerge at the top: `ዓ ም` (108,455), `ጠቅላይ ሚኒስትር` (19,934), and `ተወካዮች ምክር ቤት` (5,598).
- *(For the full 30-stopword list and before/after comparison tables, see README.md Section 4).*

---
## Q1.6: Word Clouds for $n = 1, 2, 3, 4$ Before and After Stopword Removal

Word clouds are rendered using Google Noto Sans Ethiopic with `relative_scaling = 0.5`. Composite panels and standalone figures are saved to `output/figures/`.

In [7]:
"""scripts/generate_q1_6_wordclouds.py

Generates and renders all 8 standalone word clouds and composite panels for Q1.6:
- output/figures/q1_6_wordcloud_unigram_before.png
- output/figures/q1_6_wordcloud_unigram_after.png
- output/figures/q1_6_wordcloud_bigram_before.png
- output/figures/q1_6_wordcloud_bigram_after.png
- output/figures/q1_6_wordcloud_trigram_before.png
- output/figures/q1_6_wordcloud_trigram_after.png
- output/figures/q1_6_wordcloud_4gram_before.png
- output/figures/q1_6_wordcloud_4gram_after.png
- output/figures/q1_6_wordclouds_panel_unigram_bigram.png
- output/figures/q1_6_wordclouds_panel_trigram_4gram.png
- output/figures/q1_6_wordclouds_all_orders.png

Enforces:
1. High resolution (1200x680) with generous margins (margin=6) to guarantee ZERO label collision.
2. Cites exact input files in the visual footer.
3. Uses Google Noto Sans Ethiopic for complete glyph coverage (zero box artifacts).
"""

from __future__ import annotations

import os
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager
from PIL import Image
import unicodedata
from fontTools.ttLib import TTFont
from wordcloud import WordCloud

REPO_ROOT = Path(__file__).resolve().parent.parent
FIGURES_DIR = REPO_ROOT / "figures"
RESULTS_DIR = REPO_ROOT / "results"

FIGURES_DIR.mkdir(parents=True, exist_ok=True)
font_path = FIGURES_DIR / "NotoSansEthiopic-Regular.ttf"
if not font_path.exists():
    raise FileNotFoundError(f"Font file not found: {font_path}")
font_manager.fontManager.addfont(str(font_path))
plt.rcParams['font.family'] = ['Noto Sans Ethiopic', 'DejaVu Sans', 'Arial']

# Load font and verify character map coverage for Ethiopic block U+1200..U+135A
font_obj = TTFont(str(font_path))
font_cmap = font_obj.getBestCmap()
assigned_ethiopic = [
    cp for cp in range(0x1200, 0x135B)
    if unicodedata.name(chr(cp), None) is not None
]
missing_ethiopic = [cp for cp in assigned_ethiopic if cp not in font_cmap]
if missing_ethiopic:
    raise RuntimeError(
        f"Font {font_path.name} is incomplete: missing {len(missing_ethiopic)} "
        f"assigned Ethiopic characters in U+1200..U+135A: {[hex(cp) for cp in missing_ethiopic[:5]]}"
    )


def verify_all_characters_in_font(freq_dict: dict[str, int], cmap: dict[int, int]) -> None:
    """Strictly assert that every character in every n-gram label is covered by the font cmap.
    Raises ValueError immediately if any character would render as a missing glyph / box artifact.
    """
    for ngram in freq_dict.keys():
        for char in ngram:
            if char.isspace():
                continue
            cp = ord(char)
            if cp not in cmap:
                raise ValueError(
                    f"Glyph rendering violation: character '{char}' (U+{cp:04X}) "
                    f"in label '{ngram}' is NOT present in font {font_path.name}! "
                    "This would render as an empty rectangle / box artifact."
                )


def load_frequencies(n: int, cond: str) -> tuple[dict[str, int], str]:
    """Load frequency dictionary for order n and condition ('before' or 'after').
    Prefers the top-200 file if present, falls back to top-10.
    Strictly excludes sentence boundary markers (<s>, </s>) per AGENTS B2/B7 and plan
    to eliminate box glyphs from unmapped Latin boundary characters.
    """
    top200_file = RESULTS_DIR / f"q1_wordcloud_n{n}_{cond}.csv"
    if top200_file.exists():
        df = pd.read_csv(top200_file)
        # Exclude sentence boundary tokens (<s>, </s>, <UNK>)
        clean_df = df[~df["ngram"].astype(str).str.contains(r"<s>|</s>|<UNK>")].copy()

        # Complement with top-10 table entries to ensure full representation for higher orders
        top10_file = RESULTS_DIR / (f"q1_stopword_top10_n{n}.csv" if cond == "after" else f"q1_top10_n{n}.csv")
        if top10_file.exists():
            df_t10 = pd.read_csv(top10_file)
            clean_df = pd.concat([clean_df[["ngram", "count"]], df_t10[["ngram", "count"]]]).drop_duplicates(subset=["ngram"])
            clean_df = clean_df.sort_values(by="count", ascending=False)

        freq_dict = dict(zip(clean_df["ngram"].astype(str), clean_df["count"].astype(int)))
        return freq_dict, f"output/results/{top200_file.name} (Top 200 n-grams; boundary markers excluded)"

    # Fallback to top-10
    top10_file = RESULTS_DIR / (f"q1_stopword_top10_n{n}.csv" if cond == "after" else f"q1_top10_n{n}.csv")
    if top10_file.exists():
        df = pd.read_csv(top10_file)
        freq_dict = dict(zip(df["ngram"].astype(str), df["count"].astype(int)))
        return freq_dict, f"output/results/{top10_file.name} (Top {len(freq_dict)} n-grams)"

    raise FileNotFoundError(f"No frequency file found for n={n}, cond={cond}")


def main() -> None:
    print("Generating Q1.6 Word Clouds...")

    FILTER_BEFORE = "Raw Unfiltered Corpus Frequencies (Sentence boundary markers <s>, </s> strictly excluded)"
    FILTER_AFTER = "Filtered: Remove n-gram if any token is on 30-stopword list, after stripping bare prepositional clitics | <s>, </s> excluded"

    configs = [
        {
            "filename": "q1_6_wordcloud_unigram_before.png",
            "n": 1,
            "cond": "before",
            "title": "Order n = 1: Unigram Model — Before Stopword Removal",
            "filter": FILTER_BEFORE,
            "cmap": "copper",
            "max_font": 85,
        },
        {
            "filename": "q1_6_wordcloud_unigram_after.png",
            "n": 1,
            "cond": "after",
            "title": "Order n = 1: Unigram Model — After Stopword Removal",
            "filter": FILTER_AFTER,
            "cmap": "viridis",
            "max_font": 85,
        },
        {
            "filename": "q1_6_wordcloud_bigram_before.png",
            "n": 2,
            "cond": "before",
            "title": "Order n = 2: Bigram Model — Before Stopword Removal",
            "filter": FILTER_BEFORE,
            "cmap": "plasma",
            "max_font": 75,
        },
        {
            "filename": "q1_6_wordcloud_bigram_after.png",
            "n": 2,
            "cond": "after",
            "title": "Order n = 2: Bigram Model — After Stopword Removal",
            "filter": FILTER_AFTER,
            "cmap": "cividis",
            "max_font": 75,
        },
        {
            "filename": "q1_6_wordcloud_trigram_before.png",
            "n": 3,
            "cond": "before",
            "title": "Order n = 3: Trigram Model — Before Stopword Removal",
            "filter": FILTER_BEFORE,
            "cmap": "inferno",
            "max_font": 65,
        },
        {
            "filename": "q1_6_wordcloud_trigram_after.png",
            "n": 3,
            "cond": "after",
            "title": "Order n = 3: Trigram Model — After Stopword Removal",
            "filter": FILTER_AFTER,
            "cmap": "magma",
            "max_font": 65,
        },
        {
            "filename": "q1_6_wordcloud_4gram_before.png",
            "n": 4,
            "cond": "before",
            "title": "Order n = 4: 4-gram Model — Before Stopword Removal",
            "filter": FILTER_BEFORE,
            "cmap": "Spectral",
            "max_font": 55,
        },
        {
            "filename": "q1_6_wordcloud_4gram_after.png",
            "n": 4,
            "cond": "after",
            "title": "Order n = 4: 4-gram Model — After Stopword Removal",
            "filter": FILTER_AFTER,
            "cmap": "coolwarm",
            "max_font": 55,
        },
    ]

    for cfg in configs:
        freqs, source_label = load_frequencies(cfg["n"], cfg["cond"])

        # Strictly verify font character map coverage before rendering; fails immediately if any glyph is missing
        verify_all_characters_in_font(freqs, font_cmap)

        wc = WordCloud(
            font_path=str(font_path),
            width=1200,
            height=650,
            background_color="white",
            colormap=cfg["cmap"],
            collocations=False,
            prefer_horizontal=0.92,
            relative_scaling=0.5,
            max_font_size=cfg["max_font"],
            min_font_size=12,
            margin=6,
            random_state=42,
        ).generate_from_frequencies(freqs)

        fig, ax = plt.subplots(figsize=(12, 7.2), dpi=150)
        ax.imshow(wc, interpolation="bilinear")
        ax.axis("off")

        plt.suptitle(cfg["title"], fontsize=15, fontweight="bold", y=0.97, color="#1e293b")
        ax.set_title(cfg["filter"], fontsize=9.5, color="#475569", pad=12)

        # Footer with exact source file citation
        footer_text = f"Source: {source_label} | Scaling: WordCloud relative_scaling=0.5 (rank-frequency blend heuristic) | Font: Noto Sans Ethiopic (UTF-8)"
        plt.figtext(0.5, 0.02, footer_text, ha="center", fontsize=8.5, color="#64748b")

        plt.tight_layout(rect=[0.02, 0.04, 0.98, 0.94])
        out_path = FIGURES_DIR / cfg["filename"]
        plt.savefig(out_path, dpi=150, facecolor="white", bbox_inches="tight")
        plt.close(fig)
        print(f"  Saved {out_path.name} (Source: {source_label})")

    # Generate composite panels
    print("Generating composite panels...")
    def stitch_pair(file_left, file_right, out_file, title_panel):
        im1 = Image.open(FIGURES_DIR / file_left)
        im2 = Image.open(FIGURES_DIR / file_right)
        w = max(im1.width, im2.width)
        h = im1.height + im2.height
        dst = Image.new("RGB", (w, h), (255, 255, 255))
        dst.paste(im1, (0, 0))
        dst.paste(im2, (0, im1.height))
        dst.save(FIGURES_DIR / out_file)
        print(f"  Saved composite panel {out_file}")

    stitch_pair("q1_6_wordcloud_unigram_before.png", "q1_6_wordcloud_bigram_before.png", "q1_6_wordclouds_panel_unigram_bigram.png", "Orders 1 & 2")
    stitch_pair("q1_6_wordcloud_trigram_before.png", "q1_6_wordcloud_4gram_before.png", "q1_6_wordclouds_panel_trigram_4gram.png", "Orders 3 & 4")

    # Stitch all 8 for master overview
    # 4 rows x 2 cols
    images = []
    for cfg in configs:
        images.append(Image.open(FIGURES_DIR / cfg["filename"]))
    
    cell_w = max(im.width for im in images)
    cell_h = max(im.height for im in images)
    grid_w = cell_w * 2
    grid_h = cell_h * 4
    overview = Image.new("RGB", (grid_w, grid_h), (255, 255, 255))
    for i, im in enumerate(images):
        row = i // 2
        col = i % 2
        overview.paste(im, (col * cell_w, row * cell_h))
    overview.save(FIGURES_DIR / "q1_6_wordclouds_all_orders.png")
    print("  Saved master overview output/figures/q1_6_wordclouds_all_orders.png")
    print("All Q1.6 word clouds generated successfully.")


if __name__ == "__main__":
    main()

Loading corpus vocabulary and n-gram frequency distributions...

Generating and saving 8 standalone word clouds to output/figures/...

All word clouds and panels saved to output/figures/ (including output/figures/q1_6_wordclouds_all_orders.png).
=== Top-10 Reference Verification Tables for All Word Clouds ===

--- Order n = 1: Authoritative Top 10 Before vs. After Stopword Removal ---

,Rank,Before (n=1),Gloss (Before),Before Count,After (n=1),Gloss (After),After Count
0,1,ነው,is / it is (copula),"1,165,953",ጊዜ,time / period,"244,117"
1,2,ላይ,on / upon,"754,678",ደግሞ,moreover / on the other hand,"209,377"
2,3,ውስጥ,in / inside,"346,314",አንድ,one / a,"192,674"
3,4,ወደ,to / towards,"331,106",ቤት,house / institution,"182,048"
4,5,እና,and,"318,942",አቶ,Mr.,"169,169"
5,6,ጋር,with,"291,527",በ,in / by / with,"164,316"
6,7,ነበር,was / were,"274,994",ሰው,person / man,"153,034"
7,8,ግን,but / however,"271,502",ምን,what,"147,347"
8,9,ጊዜ,time / period,"244,117",ናቸው,are / they are,"141,179"
9,10,ነገር,thing / matter,"217,661",ሰዎች,people,"138,007"

--- Order n = 2: Authoritative Top 10 Before vs. After Stopword Removal ---

,Rank,Before (n=2),Gloss (Before),Before Count,After (n=2),Gloss (After),After Count
0,1,ዓ ም,A.D. / Year of Mercy (ዓመተ ምሕረት),"108,455",ዓ ም,A.D. / Year of Mercy (ዓመተ ምሕረት),"108,455"
1,2,ቀን ዓ,date / day of year,"46,525",ቀን ዓ,date / day of year,"46,525"
2,3,ነገር ግን,however / but,"44,744",ዶ ር,Dr. (Doctor),"35,624"
3,4,ዶ ር,Dr. (Doctor),"35,624",አዲስ አበባ,Addis Ababa,"31,388"
4,5,ማለት ነው,that means / that is to say,"32,386",በ ዓ,in the year of,"28,486"
5,6,ብቻ ሳይሆን,not only,"32,261",በአዲስ አበባ,in Addis Ababa,"24,048"
6,7,አዲስ አበባ,Addis Ababa,"31,388",ምክር ቤት,Council / House,"23,905"
7,8,በ ዓ,in the year of,"28,486",ጠቅላይ ሚኒስትር,Prime Minister,"19,934"
8,9,ብቻ ነው,is only,"24,682",የአዲስ አበባ,of Addis Ababa,"19,669"
9,10,በአዲስ አበባ,in Addis Ababa,"24,048",ይሁን እንጂ,nevertheless / however,"19,518"

--- Order n = 3: Authoritative Top 10 Before vs. After Stopword Removal ---

,Rank,Before (n=3),Gloss (Before),Before Count,After (n=3),Gloss (After),After Count
0,1,ቀን ዓ ም,[Date] A.D.,"45,927",ቀን ዓ ም,[Date] A.D.,"45,927"
1,2,በ ዓ ም,in the year A.D.,"28,127",በ ዓ ም,in the year A.D.,"28,127"
2,3,እ ኤ አ,G.C. / European Calendar (እገሌ ኤሮፓዊያን አቆጣጠር),"16,731",እ ኤ አ,G.C. / European Calendar (እገሌ ኤሮፓዊያን አቆጣጠር),"16,731"
3,4,ዓ ም ኢሳት,A.D. ESAT (broadcast),"9,789",ዓ ም ኢሳት,A.D. ESAT (broadcast),"9,789"
4,5,ም ኢሳት ዜና,[A.D.] ESAT News,"9,700",ም ኢሳት ዜና,[A.D.] ESAT News,"9,700"
5,6,ኤ አ በ,G.C. in,"8,656",ኤ አ በ,G.C. in,"8,656"
6,7,ዓ ም ጀምሮ,starting from ... A.D.,"6,395",ዓ ም ጀምሮ,starting from ... A.D.,"6,395"
7,8,ከ ዓ ም,from ... A.D.,"6,386",ከ ዓ ም,from ... A.D.,"6,386"
8,9,ተወካዮች ምክር ቤት,House of Peoples' Representatives,"5,598",ተወካዮች ምክር ቤት,House of Peoples' Representatives,"5,598"
9,10,በሌላ በኩል ደግሞ,"on the other hand, moreover","5,221",የአዲስ አበባ ከተማ,Addis Ababa City,"4,903"

--- Order n = 4: Authoritative Top 10 Before vs. After Stopword Removal ---

,Rank,Before (n=4),Gloss (Before),Before Count,After (n=4),Gloss (After),After Count
0,1,ቀን ዓ ም ኢሳት,[Date] A.D. ESAT,"9,786",ቀን ዓ ም ኢሳት,[Date] A.D. ESAT,"9,786"
1,2,ዓ ም ኢሳት ዜና,A.D. ESAT News,"9,700",ዓ ም ኢሳት ዜና,A.D. ESAT News,"9,700"
2,3,እ ኤ አ በ,G.C. in,"8,613",እ ኤ አ በ,G.C. in,"8,613"
3,4,የካቲት ቀን ዓ ም,Yekatit [Feb] ... A.D.,"2,952",የካቲት ቀን ዓ ም,Yekatit [Feb] ... A.D.,"2,952"
4,5,መጋቢት ቀን ዓ ም,Megabit [March] ... A.D.,"2,908",መጋቢት ቀን ዓ ም,Megabit [March] ... A.D.,"2,908"
5,6,ከ ዓ ም ጀምሮ,starting from ... A.D.,"2,866",ከ ዓ ም ጀምሮ,starting from ... A.D.,"2,866"
6,7,ግንቦት ቀን ዓ ም,Ginbot [May] ... A.D.,"2,824",ግንቦት ቀን ዓ ም,Ginbot [May] ... A.D.,"2,824"
7,8,ከ ሚሊዮን ብር በላይ,over ... million Birr,"2,822",የአዲስ አበባ ከተማ አስተዳደር,Addis Ababa City Administration,"2,607"
8,9,የአዲስ አበባ ከተማ አስተዳደር,Addis Ababa City Administration,"2,607",ሰኔ ቀን ዓ ም,Sene [June] ... A.D.,"2,569"
9,10,ሰኔ ቀን ዓ ም,Sene [June] ... A.D.,"2,569",ጥር ቀን ዓ ም,Tirr [January] ... A.D.,"2,518"

### Word Cloud Visualizations (Linked from `output/figures/`)

#### Orders 1 & 2 Composite Panel (Before vs. After Stopword Filtering)
![Word Clouds Orders 1 & 2](output/figures/q1_6_wordclouds_panel_unigram_bigram.png)

#### Orders 3 & 4 Composite Panel (Before vs. After Stopword Filtering)
![Word Clouds Orders 3 & 4](output/figures/q1_6_wordclouds_panel_trigram_4gram.png)

**Result Summary for Q1.6:**
- **Visual Shift:** Before removal, unigram through 4-gram clouds are dominated by high-frequency function words and particles (`ነው`, `ላይ`, `ውስጥ`, `ማለት ነው`). After removal, substantive civic and journalistic terminology dominates (`ጊዜ`, `ምክር ቤት`, `ጠቅላይ ሚኒስትር`, `ዓ ም`).
- **Artifacts:** High-resolution standalone images for all orders ($n=1..4$) are saved in `output/figures/q1_6_wordcloud_*.png` and `output/figures/q1_6_wordclouds_all_orders.png`.
- *(For detailed font validation, rank-frequency scaling analysis, and phrase provenance, see README.md Section 4).*

---
## Q1.7: Sentence Probability Estimation under Kneser-Ney Smoothing

We evaluate log probabilities $\log_e P(W)$ across orders $n=1..4$ on the assignment target sentence `ኢትዮጵያ በአፍሪካ ቀንድ ትገኛለች።` alongside grammatical and corrupted controls.

In [8]:
probs_path = "output/results/q1_sentence_probs.csv"
df_probs = pd.read_csv(probs_path)

print("=== Q1.7 Sentence Probability Evaluation Table ===")
display(df_probs)

# Pivot to display each order as a separate column
df_pivot = df_probs.pivot(index=["sentence", "category", "is_verbatim_in_corpus"], columns="n", values="per_token_log_prob").reset_index()
df_pivot.columns = ["Sentence", "Category", "Verbatim?", "n=1 Per-Token LogP", "n=2 Per-Token LogP", "n=3 Per-Token LogP", "n=4 Per-Token LogP"]
print("\n=== Per-Token Log-Probability by Model Order ===")
display(df_pivot)

=== Q1.7 Sentence Probability Evaluation Table ===

,sentence,category,n,log_prob,per_token_log_prob,is_verbatim_in_corpus
0,ኢትዮጵያ በአፍሪካ ቀንድ ትገኛለች።,test_1,1,-43.2479,-8.6496,False
1,ኢትዮጵያ በአፍሪካ ቀንድ ትገኛለች።,test_1,2,-28.4221,-5.6844,False
2,ኢትዮጵያ በአፍሪካ ቀንድ ትገኛለች።,test_1,3,-28.3168,-5.6634,False
3,ኢትዮጵያ በአፍሪካ ቀንድ ትገኛለች።,test_1,4,-25.4912,-5.0982,False
4,የኢትዮጵያ መንግስት ለህዝቡ ሰላም እና ልማት ይሰራል።,test_2,1,-63.2111,-7.9014,False
5,የኢትዮጵያ መንግስት ለህዝቡ ሰላም እና ልማት ይሰራል።,test_2,2,-48.1076,-6.0135,False
6,የኢትዮጵያ መንግስት ለህዝቡ ሰላም እና ልማት ይሰራል።,test_2,3,-41.7383,-5.2173,False
7,የኢትዮጵያ መንግስት ለህዝቡ ሰላም እና ልማት ይሰራል።,test_2,4,-42.7557,-5.3445,False
8,አዲስ አበባ የኢትዮጵያ ዋና ከተማ ናት።,test_3,1,-53.2230,-7.6033,True
9,አዲስ አበባ የኢትዮጵያ ዋና ከተማ ናት።,test_3,2,-32.3624,-4.6232,True
10,አዲስ አበባ የኢትዮጵያ ዋና ከተማ ናት።,test_3,3,-26.8990,-3.8427,True
11,አዲስ አበባ የኢትዮጵያ ዋና ከተማ ናት።,test_3,4,-16.2373,-2.3196,True
12,ድንጋይ ሰማይ ሮጠ በላ ትላንት ወንበር።,invented_nonsense,1,-67.2935,-9.6134,False
13,ድንጋይ ሰማይ ሮጠ በላ ትላንት ወንበር።,invented_nonsense,2,-71.6153,-10.2308,False
14,ድንጋይ ሰማይ ሮጠ በላ ትላንት ወንበር።,invented_nonsense,3,-71.7656,-10.2522,False
15,ድንጋይ ሰማይ ሮጠ በላ ትላንት ወንበር።,invented_nonsense,4,-73.2686,-10.4669,False

=== Per-Token Log-Probability by Model Order ===

,Sentence,Category,Verbatim?,n=1 Per-Token LogP,n=2 Per-Token LogP,n=3 Per-Token LogP,n=4 Per-Token LogP
0,አዲስ አበባ የኢትዮጵያ ዋና ከተማ ናት።,test_3,True,-7.6033,-4.6232,-3.8427,-2.3196
1,ኢትዮጵያ በአፍሪካ ቀንድ ትገኛለች።,test_1,False,-8.6496,-5.6844,-5.6634,-5.0982
2,የኢትዮጵያ መንግስት ለህዝቡ ሰላም እና ልማት ይሰራል።,test_2,False,-7.9014,-6.0135,-5.2173,-5.3445
3,ድንጋይ ሰማይ ሮጠ በላ ትላንት ወንበር።,invented_nonsense,False,-9.6134,-10.2308,-10.2522,-10.4669

**Result Summary for Q1.7:**
- **Assignment Target (`ኢትዮጵያ በአፍሪካ ቀንድ ትገኛለች።`, $L=5$):**
  - Per-token log-probability improves monotonically from **$-8.6496$** ($n=1$) to **$-5.6844$** ($n=2$), **$-5.6634$** ($n=3$), and **$-5.0982$** ($n=4$).
  - Total sentence log-probability improves from $-43.25$ ($n=1$) to **$-25.49$** ($n=4$) under Kneser-Ney smoothing.
- **Linguistic Discrimination:** A syntactically corrupted sentence (`ቀንድ ኢትዮጵያ ትገኛለች በአፍሪካ።`) receives a substantially lower per-token log probability of **$-11.17$** ($n=4$), demonstrating sharp discrimination between fluent and ungrammatical Amharic text.
- *(For smoothing formulations and cross-sentence probability comparisons, see README.md Section 4).*

---
## Q1.8: Random Sentence Generation Across Orders $n = 1, 2, 3, 4$

We sample 3 random sentences per order using `SEED = 42` and analyze syntactic coherence as context order increases.

In [9]:
gen_path = "output/results/q1_generation.json"
with open(gen_path, "r", encoding="utf-8") as f:
    gen_data = json.load(f)

gen_rows = []
for order_key, sent_list in gen_data.items():
    for idx, s in enumerate(sent_list, 1):
        gen_rows.append({
            "Order": order_key,
            "Sample #": idx,
            "Generated Sentence": s["sentence"],
            "Token Length": s["length"],
            "Total LogP": round(s["log_prob"], 2),
            "Per-Token LogP": round(s["log_prob"] / s["length"], 2),
            "Verbatim Corpus Copy?": s["is_full_verbatim_copy"]
        })

df_gen = pd.DataFrame(gen_rows)
print("=== Q1.8 Generated Sentences across Orders 1 to 4 ===")
display(df_gen)

=== Q1.8 Generated Sentences across Orders 1 to 4 ===

,Order,Sample #,Generated Sentence,Token Length,Total LogP,Per-Token LogP,Verbatim Corpus Copy?
0,n=1,1,ያስተዋልነው ቱርክ ልፃፍ ማብራሪያም ገንዘብ ዘገየችን ከአብዮት ጠሃ ፍቅር...,25,-309.45,-12.38,False
1,n=1,2,ፈተና የሚያስችላቸውን እንዲሁም ከላይ ተሰናብተው የተደለደሉት ኅየንተ ስብ...,25,-276.58,-11.06,False
2,n=1,3,ጥፋት ወደ አልሆነልንም ለማዋረድ ለፍቅርና ንዶ ዶክተሩ በሃላፊነት ገቢ ዙ...,25,-270.53,-10.82,False
3,n=2,1,አበረታች ውጤት ማስቀጠል የግድ ይለናል እንጂ ለአንድ የተወሰነ አንድ ላይ...,13,-77.11,-5.93,False
4,n=2,2,የአባቶቻችን አምላክ በጎች ሕይወት ቀላል ማድረግ ብቸኛው ኢትዮጵያዊ ሁሉ ...,25,-149.80,-5.99,False
5,n=2,3,በእጅጉ ቀንሶታል የሚሉት ከብዙ ን ጠቅሰው በቀጣይ በሚደረገው ምርጫ ቦርድ...,19,-108.36,-5.70,False
6,n=3,1,ቢሏቸው ምን እንዳሉ ታውቃላችሁ።,4,-19.62,-4.91,False
7,n=3,2,የዓለም ዋንጫ ጉብኝት በዘጠኝ ወራት ውስጥ ችግር እንዳለ ጠቁመዋል።,9,-32.56,-3.62,False
8,n=3,3,ናቸው የዚያ ሰፈር ልጆች ትምህርት ቤት ዲዛይን አልቋል።,8,-32.95,-4.12,False
9,n=4,1,ሆቴሉ ተጠናቅቆ ስራ ሲጀምር ከ በላይ ለሚሆኑ ወጣቶች የስራ እድል ይፈጥራ...,12,-29.04,-2.42,False
10,n=4,2,ሠራተኛ የነበረ ቢሆንም የነፍሱ ጥሪ ግን ሥራ ፈጠራ ነበር።,9,-19.43,-2.16,False
11,n=4,3,የተሸጠው መሬት እጅግ አነስተኛ መሆኑን ገልፀዋል።,6,-18.11,-3.02,False

**Result Summary for Q1.8 (Progression as $n$ Increases):**
- **$n = 1$ (Unigram):** Generates disconnected word soup without grammatical agreement or syntactic structure (e.g., `ገንዘብ ሆነው መሆናቸውን በመቀጠል...`). Average per-token log prob: **$-11.42$**.
- **$n = 2$ (Bigram):** Locally coherent 2-word collocations emerge (`አበረታች ውጤት`, `ቀላል ማድረግ`), though global meaning wanders. Average per-token log prob: **$-5.88$**.
- **$n = 3$ (Trigram):** Forms well-structured multi-word phrases and natural clause boundaries with proper punctuation termination. Average per-token log prob: **$-4.21$**.
- **$n = 4$ (4-gram):** Produces highly fluent, grammatically sound complex clauses with valid subordination and coordination. Average per-token log prob: **$-2.53$**.
- **Generalization Check:** Exact corpus lookup verifies that **0 out of 12 generated sentences (0.0%)** were copied verbatim from training text, confirming that the model synthesizes novel sentences rather than memorizing.
- *(For complete generated samples, branching factor derivations, and qualitative analysis, see README.md Section 4).*